
/vis/open OGL 600x600-0+0

/vis/drawVolume
/vis/viewer/set/style wireframe

/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

# Axes, scale, etc.
/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo
/vis/scene/add/logo    # 3D logo

