//--------------------------LIST OF PARAMETETRS-------------------------
:P ORIGIN -50*cm
:P FIELD 10*cm
:P DSP 100*cm
//WORLD
:P WORLD_DIM_X 50*cm
:P WORLD_DIM_Y 50*cm
:P WORLD_DIM_Z 100*cm
//TARGET
:P TARGET_DIM_Z 0.5*cm
:P TARGET_DIM_Y 4*cm
:P TARGET_DIM_X 4*cm
// PRIMARY_COLLIMATOR
:P RMAX 10*cm
:P PC_ZMIN 1.6*cm
:P PC_ZMAX 7.6*cm
:p JAWS_DIM_X 10*cm
:P THETA atan($FIELD/$DSP)/deg
:p JAWS_DIM_Z 5*cm
:p JAWS_DIM_Y 10*cm
:P JAWSX_POSITION_CENTER_Z 30*cm
:P DISTANCE_SOURCE_JAWSX ($JAWSX_POSITION_CENTER_Z+$JAWS_DIM_X/2.0)
:P DX $DISTANCE_SOURCE_JAWSX*tan($THETA*deg/2.0)
:P JAWSX_POSITION_CENTER_X $JAWS_DIM_X+$DX
:p JAWSY_POSITION_CENTER_Z 40*cm
:P DISTANCE_SOURCE_JAWSY ($JAWSY_POSITION_CENTER_Z+$JAWS_DIM_Y/2.0)
:P dy $DISTANCE_SOURCE_JAWSY*tan($THETA*deg/2.0)
:P JAWSY_POSITION_CENTER_Y ($JAWS_DIM_Y+$dy)
:ROTM RM0          0           0          0
:ROTM RM_JAW_X1    0           $THETA*deg 0
:ROTM RM_JAW_Y1    $THETA*deg  0          0
:ROTM RM_JAW_X2    0          -$THETA*deg 0
:ROTM RM_JAW_Y2   -$THETA*deg  0          0
//FLATTENING_FILTER
:P FLATTENING_FILTER_CENTER_Z 8*cm
// MONITOR
:P MONITOR_Z_POS 15*cm
:P MONITOR_R_MAX 10*cm
:P MONITOR_R_MIN 0*cm
:P MONITOR_CENTER_Z 1.5*cm
//PHASE_SPACE
:P PHASE_SPACE_DIM_Z 0.0001*cm
:P PHASE_SPACE_DIM_Z_STOP 100*cm
:P PHASE_SPACE_ORIGIN_Z  $PHASE_SPACE_DIM_Z+$PHASE_SPACE_DIM_Z_STOP

//--------------------------LIST OF VOLUMES-------------------------
// WORLD
:VOLU WORLD BOX $WORLD_DIM_X/2.0 $WORLD_DIM_Y/2.0 $WORLD_DIM_Z/2.0 G4_AIR
:VIS WORLD OFF

// TARGET 
:VOLU TARGET BOX $TARGET_DIM_X/2.0 $TARGET_DIM_Y/2.0 $TARGET_DIM_Z/2.0 G4_Cu
:COLOR TARGET  1 0 0
:PLACE TARGET  1 WORLD RM0 0.0 0.0 $TARGET_DIM_Z/2.0+$ORIGIN

//PRIMARY COLLIMATOR
:VOLU  "PRIMARY_COLLIMATOR_0" TUBE 0 $RMAX ($PC_ZMAX-$PC_ZMIN)/2. G4_W
:COLOR "PRIMARY_COLLIMATOR_0"  0 1 0
:VOLU  "PRIMARY_COLLIMATOR_1" CONE 0 4 0 20 ($PC_ZMAX-$PC_ZMIN)/2. G4_AIR
:COLOR "PRIMARY_COLLIMATOR_1"  0.5 0.5 0.5
:PLACE "PRIMARY_COLLIMATOR_0"  1 WORLD RM0  0. 0. ($PC_ZMIN+$PC_ZMAX)/2.+$ORIGIN
:PLACE "PRIMARY_COLLIMATOR_1"  1 "PRIMARY_COLLIMATOR_0"  RM0  0. 0. 0. 

// FLATTENING_FILTER
:MIXT SiFeMn 8. 3 G4_Si 1./3. G4_Fe 1./3. G4_Mn 1./3.
:VOLU  "FLATTENING_FILTER" POLYCONE 0. 360.*deg 5 0. 0. 1.25 10. 0. 9. 17. 0. 13.8 17. 0. 27.8 18. 0. 27.8 SiFeMn
:PLACE "FLATTENING_FILTER" 0 WORLD RM0 0. 0. $FLATTENING_FILTER_CENTER_Z+$ORIGIN
:COLOR "FLATTENING_FILTER"  0.2 1 0.5
// MONITOR
:VOLU MONITOR TUBE $MONITOR_R_MIN $MONITOR_R_MAX $MONITOR_CENTER_Z G4_AIR
:PLACE MONITOR 1 WORLD RM0 0. 0. $MONITOR_Z_POS+$ORIGIN
:COLOR MONITOR  0.5 0.25 1.0
// PHASE_SPACE
:VOLU PHASE_SPACE BOX $WORLD_DIM_X/2.0 $WORLD_DIM_Y/2.0 $PHASE_SPACE_DIM_Z G4_AIR
:COLOR PHASE_SPACE  1 0 0
:PLACE PHASE_SPACE 1 WORLD RM0 0. 0. $PHASE_SPACE_ORIGIN_Z+$ORIGIN

// JAWS
:VOLU JAWS_X1 BOX $JAWS_DIM_X $JAWS_DIM_Y $JAWS_DIM_Z G4_W 
:COLOR JAWS_X1  1 0 1
:PLACE JAWS_X1 1 WORLD RM_JAW_X1 -$JAWSX_POSITION_CENTER_X 0. $JAWSX_POSITION_CENTER_Z+$ORIGIN

:VOLU JAWS_X2 BOX $JAWS_DIM_X $JAWS_DIM_Y $JAWS_DIM_Z G4_W 
:COLOR JAWS_X2  1 0 1
:PLACE JAWS_X2 1 WORLD RM_JAW_X2 $JAWSX_POSITION_CENTER_X 0. $JAWSX_POSITION_CENTER_Z+$ORIGIN

:VOLU JAWS_Y1 BOX $JAWS_DIM_X $JAWS_DIM_Y $JAWS_DIM_Z G4_W 
:COLOR JAWS_Y1  1 0 1
:PLACE JAWS_Y1 1 WORLD RM_JAW_Y1 0. $JAWSY_POSITION_CENTER_Y  $JAWSY_POSITION_CENTER_Z+$ORIGIN

:VOLU JAWS_Y2 BOX $JAWS_DIM_X $JAWS_DIM_Y $JAWS_DIM_Z G4_W 
:COLOR JAWS_Y2  1 0 1
:PLACE JAWS_Y2 1 WORLD RM_JAW_Y2 0. -$JAWSY_POSITION_CENTER_Y  $JAWSY_POSITION_CENTER_Z+$ORIGIN
